# Generated by Django 3.2.5 on 2021-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подназвание поста')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
